//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalStaffingSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Timesheet_summaries = new HashSet<Timesheet_summaries>();
        }
    
        public int Id { get; set; }
        public string Employee_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Middle_name { get; set; }
        public Nullable<int> Organization_id { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<int> Branch_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<bool> Internal_employee { get; set; }
        public Nullable<System.DateTime> Anniversary_date { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Status { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Marital_status { get; set; }
        public string Gender { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<System.DateTime> Hire { get; set; }
        public Nullable<System.DateTime> ReHire { get; set; }
        public Nullable<System.DateTime> ENTITY_ADDED_AT { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timesheet_summaries> Timesheet_summaries { get; set; }
    }
}
