//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalStaffingSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Po_Numbers
    {
        public int Id { get; set; }
        public string PoNumber { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Client_Generic_Id { get; set; }
    }
}
