//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalStaffingSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectedTimesheet
    {
        public int Id { get; set; }
        public Nullable<int> TimeSheetId { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<int> RejecetedByCustomerId { get; set; }
        public Nullable<System.DateTime> RejectedAt { get; set; }
        public Nullable<bool> IsUpdatedOrDeleted { get; set; }
    }
}
