//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalStaffingSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet_summaries
    {
        public int Id { get; set; }
        public Nullable<int> Timesheet_id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string Rate { get; set; }
        public string Enitial { get; set; }
        public Nullable<double> Total_hours { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<int> Rating_by_client { get; set; }
        public Nullable<double> Hours_day_1 { get; set; }
        public Nullable<double> Hours_day_2 { get; set; }
        public Nullable<double> Hours_day_3 { get; set; }
        public Nullable<double> Hours_day_4 { get; set; }
        public Nullable<double> Hours_day_5 { get; set; }
        public Nullable<double> Hours_day_6 { get; set; }
        public Nullable<double> Hours_day_7 { get; set; }
        public Nullable<System.DateTime> Starting_date { get; set; }
        public Nullable<System.DateTime> Ending_date { get; set; }
        public Nullable<int> Starting_day_of_week { get; set; }
        public Nullable<int> Ending_day_of_week { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Timesheet Timesheet { get; set; }
    }
}
