//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalStaffingSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.User_Branches = new HashSet<User_Branches>();
        }
    
        public int Id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Address { get; set; }
        public string Phone_number { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public System.DateTime Created_at { get; set; }
        public System.DateTime Updated_at { get; set; }
        public string Email { get; set; }
        public string Encrypted_password { get; set; }
        public string Reset_password_token { get; set; }
        public Nullable<System.DateTime> Reset_password_sent_at { get; set; }
        public Nullable<System.DateTime> Remember_created_at { get; set; }
        public int Sign_in_count { get; set; }
        public Nullable<System.DateTime> Current_sign_in_at { get; set; }
        public Nullable<System.DateTime> Last_sign_in_at { get; set; }
        public string Current_sign_in_ip { get; set; }
        public string Last_sign_in_ip { get; set; }
        public string Invitation_token { get; set; }
        public Nullable<System.DateTime> Invitation_created_at { get; set; }
        public Nullable<System.DateTime> Invitation_sent_at { get; set; }
        public Nullable<System.DateTime> Invitation_accepted_at { get; set; }
        public Nullable<int> Invitation_limit { get; set; }
        public Nullable<int> Invited_by_id { get; set; }
        public string Invited_by_type { get; set; }
        public Nullable<int> Invitations_count { get; set; }
        public Nullable<bool> Internal_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Branches> User_Branches { get; set; }
    }
}
